services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG=${DEBUG:-false}
      - WHOIS_SERVER=${WHOIS_SERVER:-whois.verisign-grs.com}
      - WHOIS_PORT=${WHOIS_PORT:-43}
      - WHOIS_TIMEOUT=${WHOIS_TIMEOUT:-10}
    volumes:
      - .:/var/www
    networks:
      - whois-network
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - whois-network
networks:
  whois-network:
    driver: bridge
